services:
  - type: web
    name: promptgenie-backend
    env: python
    rootDir: backend

    buildCommand: pip install -r requirements.txt

    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000

    envVars:
      - key: MONGO_URI
        sync: false

      - key: SECRET_KEY
        sync: false

      - key: GEMINI_API_KEY
        sync: false

      - key: EMAIL_USER
        sync: false

      - key: EMAIL_PASS
        sync: false

      - key: BASE_URL
        sync: false

  - type: web
    name: promptgenie-frontend
    env: static
    rootDir: frontend

    buildCommand: flutter build web

    staticPublishPath: build/web

    envVars:
      - key: API_BASE_URL
        sync: false